# Generated by Django 4.2.7 on 2023-12-04 20:52

import Lock.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='schedulled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='secret',
            field=models.CharField(default=Lock.models.generate_secret, max_length=72),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='status',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Lock.terminal')),
            ],
        ),
    ]
