# Generated by Django 4.2.5 on 2023-10-01 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='terminal',
            field=models.ForeignKey(default='923cd9ca-6f7d-4cee-9a2c-5a74e2b55801', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='Lock.terminal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terminal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to=settings.AUTH_USER_MODEL),
        ),
    ]
